version: "3"

services:
  webserver:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      PROFILE: "local"
      SOME_NAME: "Google APIs"
      SOME_URL: "https://developers.google.com/apis-explorer"
